# Generated by Django 2.2.1 on 2019-05-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofitsiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='created',
        ),
        migrations.RemoveField(
            model_name='client',
            name='descriptions',
        ),
        migrations.AddField(
            model_name='client',
            name='ovqat_choice',
            field=models.CharField(blank=True, choices=[('Mastava', 'mastava'), ('shorva', 'shorva'), ('chuchvara', 'chuchvara')], max_length=12, null=True),
        ),
    ]
