# Generated by Django 2.2.1 on 2019-05-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20190524_0121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ovqat_choice',
            new_name='birinchi_ovqat',
        ),
        migrations.AddField(
            model_name='client',
            name='ichimlik',
            field=models.CharField(blank=True, choices=[('Pepsi', 'Pep'), ('Coca Cola', 'Coca Cola'), ('kofe', 'kofe')], max_length=12, null=True),
        ),
    ]
