# Generated by Django 2.2.1 on 2019-05-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20190524_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ikkinchi_ovqatlar',
            field=models.CharField(blank=True, choices=[('osh', 'osh'), ('bishteks', 'bishteks'), ('asortiment', 'asortiment')], max_length=12, null=True),
        ),
    ]
