# Generated by Django 2.2.1 on 2019-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20190525_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofitsiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakaz', models.ManyToManyField(to='restaurant.client')),
            ],
        ),
    ]
