# Generated by Django 2.2.1 on 2019-05-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_ofitsiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='oshpaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakazlar', models.ManyToManyField(to='restaurant.ofitsiant')),
            ],
        ),
    ]
