# Generated by Django 2.2.1 on 2019-05-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_oshpaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oshpaz',
            name='zakazlar',
            field=models.ManyToManyField(to='restaurant.client'),
        ),
    ]
